name: authentication_infrastruture
description: The interface and models for an API providing access to users.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^4.0.0
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  meta: ^1.3.0
  injectable: ^1.5.0
  authentication_domain:
    path: ../domain
  utils:
    path: ../utils

dev_dependencies:
  # build_runner: ^2.0.0
  json_serializable: ^6.0.0
  # flutter_lints: ^1.0.0